config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'root#top'
  get '/books' => 'books#index'

  post '/books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  	@book = Book.new
  	@books = Book.all
  end

  def create
  	book = Book.new(book_params)
  	if book.save
      flash[:notice] = "successfully"
    end

    redirect_to book_path(book.id)
    
  end


  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully"
    end

    redirect_to book_path(@book.id)

  end

  def destroy
    @books = Book.find(params[:id])
    @books.destroy
    redirect_to books_path
  end

   private
    def book_params
        params.require(:book).permit(:title, :body)
    end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
	def top
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>


<%= form_for(@book) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title, class: "book_title" %>
    <h4>Body</h4>
    <%= f.text_area :body, class: "book_body" %>
	<div>
	    <%= f.submit 'Update Book' %>
	</div>




<%= link_to "Show", book_path(@book.id),class: "show_#{@book.id}" %>

 <span>|</span>


<%=link_to"Back", "/books",class: "back" %>



<% end %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <tr>
	<th>Title</th>
	<th>Body</th>

  </tr>


	<tr>
	<% @books.each do |book| %>


	<td><%= book.title %></td>
	<td><%= book.body %></td>
	<td><%= link_to "Show", book_path(book.id), class: "show_#{book.id}" %></td>
	<td><%= link_to "Edit", edit_book_path(book.id), class: "edit_#{book.id}" %></td>
	<td><%= link_to "Destroy",destroy_book_path(book.id), class: "destory_#{book.id}", method: :delete, "data-confirm" =>"Are you sure?" %></td>

	</tr>
	<% end %>


</table>


<div>

	<h3>New book</h3>

	<%= form_for(@book) do |f| %>

		<h4>Title</h4>
		<%= f.text_field :title,class: "book_title" %>

		<h4>body</h4>
		<%= f.text_area :body,class: "book_body" %>
	<div>
		<%= f.submit 'Create Book' %>
		
	</div>
	<% end %>
</div>

app/views/books/show.html.erb
<p><b>Title: </b><%= @book.title %></p>

<p><b>Body: </b><%= @book.body %></p>


<p>

<%= link_to "Edit", edit_book_path(@book.id),class: "edit_#{@book.id}" %>

 <span>|</span>


<%=link_to"Back", "/books",class: "back" %>


</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/root/top.html.erb
<h1>ようこそ Bookers へ！</h1>
<h4>Bookers では、さまざまな書籍に関するあなたの意見や</h4>

<h4>印象を共有し交換することができます</h4>

<p>
 <%=link_to"start", "/books" %>

</p>